### ISSUE TITLE
Adding an navigation bar

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/Upcharika#10]
Add the bottom of the screen adding we can have a navigation bar specifying all the required values in it:

1. Reports/Dashboard
2. Hear Rate
3. SPo2 levels
4. Home

if any other value should be present in this bar do mention it.

**Comment by sakshiisaxena** [comment]
Hey, @anushbhatia could you please assign me this issue?

**Comment by anushbhatia** [comment]
Assigned for 4 days

**Comment by Sarthak-Singh02** [comment]
I want to work on this issue.

**Comment by anushbhatia** [comment]
Sure @Sarthak-Singh02
