### ISSUE TITLE
Store various values for heart Rate

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/Upcharika#13]
To store the values of the user as soon he clicks the stop button maintains the details of all days when it was used.
You can ask for local storage for them and store it on a new page/excel/word any document.

**Comment by Priyanshu078** [comment]
please assign me this issue

**Comment by smaranjitghose** [comment]
Assigned for 3 days

**Comment by Priyanshu078** [comment]
@anushbhatia @smaranjitghose I am saving the heart rate with the date and time of measurement in a text file, and if the user wants to see the values of his/her heart rate then I am thinking to make a list view of the values and show to the user.

**Comment by anushbhatia** [comment]
LGTM.

**Comment by Priyanshu078** [comment]
@anushbhatia What

**Comment by Priyanshu078** [comment]
I was not able to understand

**Comment by smaranjitghose** [comment]
> I was not able to understand

It means you can go ahead

**Comment by Priyanshu078** [comment]
oh! Thanks
