### ISSUE TITLE
Add Let'sGrowMore logo under 'Open Source Program' section

### ISSUE THREAD

**Issue by Ayan-thecodeking** [smaranjitghose/Upcharika#15]
Since this project is part of LGMSOC . I think it's good ideI will like to work on this issue under LGMSOC if maintainers agreea to showcase it in README.md file under Open Source Program section . @smaranjitghose

**Comment by smaranjitghose** [comment]
These are things to be done by the project maintainers over the course of the program or perhaps later. Please focus on contributing to the actual codebase
