### ISSUE TITLE
Exit BPM process 

### ISSUE THREAD

**Issue by Priyanshu078** [smaranjitghose/Upcharika#18]
Exit BPM estimating process when the app goes in the background.v

**Comment by Priyanshu078** [comment]
Because it should stop estimating the BPM when the app loses focus or it is in the background.
PLease assign me this issue

**Comment by anushbhatia** [comment]
Sure do give regular updates. Assigned for 4 days

**Comment by Priyanshu078** [comment]
@anushbhatia I have committed the code for this issue and it is joined in the same pull request which was there for 
exit flash bug.

**Comment by Priyanshu078** [comment]
@anushbhatia Sir for this issue the code is merged with the code of the adding timer issue.
Will I be graded for both the issues or only for one

**Comment by anushbhatia** [comment]
Both
