### ISSUE TITLE
Timer Enhancement

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/Upcharika#22]
To add a visual effect of the timer a circular progress bar. So that user can know how much time is left.
[Some Refrence](https://medium.com/flutterdevs/creating-a-countdown-timer-using-animation-in-flutter-2d56d4f3f5f1)

**Comment by SanjayDevTech** [comment]
Could you assign me this issue

**Comment by anushbhatia** [comment]
Assigned for 3 days

**Comment by SanjayDevTech** [comment]
Please review the PR #37 
Thanks : )
