### ISSUE TITLE
On Board Screen Logic

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/Upcharika#26]
When the user has downloaded the app for the first time add an option to display the onboarding screen otherwise skip that screen direct to the home screen.

**Comment by Priyanshu078** [comment]
please assign me this issue

**Comment by anushbhatia** [comment]
Assigned for 3 days.

**Comment by dhivya17** [comment]
Kindly assign me this if its still open

**Comment by smaranjitghose** [comment]
Sorry @dhivya17 . This issue was resolved
