### ISSUE TITLE
Adding an appropriate app icon

### ISSUE THREAD

**Issue by Procoder16** [smaranjitghose/Upcharika#31]
All the flutter apps are given the default flutter app icon which is supposed to be changed here.

1. Convert the image into an app icon
2. Make the required changes.
<img width="256" alt="nurse" src="https://user-images.githubusercontent.com/71066110/123320430-5af3ec80-d54f-11eb-9881-26dbb15d9f0c.png">

**Comment by Priyanshu078** [comment]
Please assign me this issue

**Comment by Procoder16** [comment]
> Please assign me this issue

This was already an "Up for Grab" issue. Go ahead👍
