### ISSUE TITLE
Improve UI for home Screen

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/Upcharika#4]
Adding an illustration below the buttons which describe the medical aspect of this project.
 
 You can create your own Illustration or refer this https://undraw.co/

**Comment by dibyanshu-mohanty** [comment]
I would like to work on this issue

**Comment by aviralguptaa** [comment]
I would like to work on this issue. Please assign this to me.

**Comment by aviralguptaa** [comment]
I would like to work on this issue and create a beautiful UI for the app. Please assign this to me.

**Comment by Procoder16** [comment]
@aviralguptaa Can you mention what changes to the UI will you add? Actually, the issue that was raised is already done but still, a lot of changes can be made.

**Comment by ayyysh04** [comment]
I would like to work on this task.

**Comment by abhishektiwari47** [comment]
I want to work on this. I am an SDE intern at a startup which working on flutter and I think I can contribute to this issue

**Comment by anushbhatia** [comment]
Sure @abhishektiwari47 go ahead. Also provide libraries if any external ones used

**Comment by abhishektiwari47** [comment]
Thanks, I am working on it.
