### ISSUE TITLE
Improving the design of bottom navigation bar

### ISSUE THREAD

**Issue by ayyysh04** [smaranjitghose/Upcharika#44]

**Comment by abhishektiwari47** [comment]
I want to work on this. I am an SDE intern at a startup which working on flutter and I think I can contribute to this issue

**Comment by vaibav03** [comment]
Can I take up this issue?

**Comment by VishalVinayRam** [comment]
I would like to work on this

**Comment by Sarthak-Singh02** [comment]
I want to work on this, I have made a full fledge e-book app using flutter and firebase.
