### ISSUE TITLE
Adding a splash screen

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/Upcharika#5]
Currently, we don't have a splash screen for our project it would be convenient to have so.

**Comment by karanpatel2329** [comment]
I am willing to work on this issue. Please assigned it to me.

**Comment by smaranjitghose** [comment]
Assigned for 3 days to @karanpatel2329

**Comment by karanpatel2329** [comment]
Uploading splash-screen.mp4

Here clip of Splash Screen. 
I am unable to join slack. can you help me.

**Comment by karanpatel2329** [comment]
![splash screen](https://user-images.githubusercontent.com/51056125/122154520-d0dac280-ce82-11eb-83a9-394b6da6c9fe.jpeg)
![homepage](https://user-images.githubusercontent.com/51056125/122154521-d2a48600-ce82-11eb-8223-8de2b30fdfa0.jpeg)
