### ISSUE TITLE
Adding a timer on heart rate screen

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/Upcharika#7]
To add a 30 to a 60-second timer so that the user has to keep his finger there till the accurate readings are obtained.
Indicating to remove the finger or to automatically stop the process at that time.

or you can indicate time on the button so that they will when they can remove their finger.

**Comment by Priyanshu078** [comment]
please assign me this issue

**Comment by smaranjitghose** [comment]
Assigned for 3 days

**Comment by Priyanshu078** [comment]
@smaranjitghose @anushbhatia can I commit the code of this issue in the same in the same pull request

**Comment by smaranjitghose** [comment]
Make a new PR

**Comment by Priyanshu078** [comment]
@smaranjitghose but not able to make it because there is the PR in the pull requests section please merge it.

**Comment by smaranjitghose** [comment]
Make the changes for this issue in a separate branch

**Comment by Priyanshu078** [comment]
Ok thankyou
