### ISSUE TITLE
Adding Dark Mode

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/Upcharika#9]
Currently, we don't have a dark mode for that app.
For references and colour codes you can refer this https://github.com/smaranjitghose/DocLense
Either add the button in the navigation bar or create that in-app bar.

**Comment by pratishthaa** [comment]
Can I be assigned this issue?

**Comment by smaranjitghose** [comment]
Assigned for 3 days

**Comment by noman2002** [comment]
If anyone is  not working. Can I work on this.?

**Comment by Procoder16** [comment]
@noman2002 sure!!!

**Comment by noman2002** [comment]
Please assign it to me.
@Procoder16
